# Generated by Django 4.2.4 on 2023-09-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_members_server_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='member',
            new_name='members',
        ),
    ]
